version: "3.8"

services:
  app:
    build: .
    environment:
      - HTTPPORT=8081
      - LOGLEVEL=debug
    platform: linux/amd64
    ports:
      - "39001:8081"
    volumes:
      - storage:/usr/share/snf-server/storage/
  sniffer:
    image: public.ecr.aws/mailprotector/sniffer:latest
    platform: linux/amd64
    volumes:
      - storage:/usr/share/snf-server/storage/
    environment:
      - LICENSE=[redacted]
      - AUTH=[redacted]
    network_mode: "service:app"
volumes:
  storage:
