version: "3.8"

services:
  app:
    build: .
    depends_on:
      - sniffer
    ports:
      - "8080:8080"
    volumes:
      - storage:/usr/share/snf-server/storage/
  sniffer:
    image: sniffer:latest
    volumes:
      - storage:/usr/share/snf-server/storage/
    environment:
      - LICENSE='ouqpmlwq'
      - AUTH='gfbyrubr83kga2i5'
    expose:
      - "9001"
volumes:
  storage:
